spring.application.name=clean-nice-app
spring.datasource.url=jdbc:postgresql://ep-little-butterfly-zah9lpt4-pooler.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate